### ISSUE TITLE
Not persistent through page update

### ISSUE THREAD

**Issue by icodk** [Download/memorystorage#13]
Using it in Chrome on Windows 10,  MemoryStorage object is reset after each page update.
Should it persist  across updates ?

**Comment by Download** [comment]
No, it is *memorystore*.

The purpose of this library is to provide an API compatible with the Web Storage API, so that you can use the Web Storage API in all environments.

The idea here is:
* Detect if Web Storage is available*. If so: Yippee, use it.
* If not: Instantiate a MemoryStorage and use that instead.

**But what is the point?**
On some browsers (looking at you, Safari!) the storage api actually throws exceptions in Private Browsing / Incognito mode. It would have been so much better if they would have done the same as Chrome and Firefox (and as is already done for cookies) just store the data in the session only and throw it away as soon as the browser is closed. But alas, 'some browser' throws exceptions so we need to either catch exceptions everywhere, or switch to some other api etc. Or, we shim the 'broken' storage object with MemoryStorage, which at least makes everything work on the page.

**But I NEED persistence!**
What you could do is implement a fallback to cookies. These persist across the session even in incognito mode. But cookies only allow a few kB of storage so not suitable if you have more data. So I did not do this. 

So you can see MemoryStorage as just an implementation of the Web Storage API that saves it's data in memory only. You could make CookieStorage for example. Or (on NodeJS) FileStorage. Etc. See also https://github.com/Download/memorystorage/issues/8

> * You can detect if storage is available using [storage-available](https://github.com/Download/storage-available)

**Comment by icodk** [comment]
Thanks...But:-) in Chrome the Web storage API works fine, still using MemoryStorage do not persist
as as it should:
> Detect if Web Storage is available*. If so: Yippee, use it
What am I missing ?
.

**Comment by icodk** [comment]
I think I got it
I have to  detect if Web storage is available ?

**Comment by Download** [comment]
You have to understand that the purpose of MemoryStorage is not primary storage. It is used as a shim/stub (for in tests etc) or as a last-resort fallback for when there simply is no good alternative such as in Safari private browser mode.

So yes, you have to simply use localStorage when possible and only fall back to memorystorage when that is not available. This example code uses the test in [storage-available](https://npmjs.com/package/storage-available):

```js
var MemoryStorage = require('memorystorage');
var storageAvailable = require('storage-available');

var storage = storageAvailabe('localStorage') ? localStorage : new MemoryStorage('my-app');

storage.setItem('my-name', 'my-value');
console.info('my-name: ', storage.getItem('my-name'));  
// logs:  'my-value'
```

This way you can more or less ignore runtimes that do not have `localStorage`. This code should run fine under Node JS for example.
